[metadata]
name = fateml
version = 0.0.20
author = Tamás Ficsor
author_email = ficsort@inf.u-szeged.hu
description = Utilities for the notebooks
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/ficstamas/FateML
project_urls =
    Bug Tracker = https://github.com/ficstamas/FateML/issues
classifiers =
    License :: OSI Approved :: MIT License
    Programming Language :: Python :: 3

[options]
packages = find:
python_requires = >=3.10
install_requires =
    pandas>=2.2
    numpy==2.2.*
    scikit-learn==1.8.*
    scipy==1.16.*
    matplotlib>=3.10
    seaborn==0.13.*
    lxml>=6.0
    cvxopt>=1.3
    imodels>=2.0
    graphviz>=0.21
    anchor-exp
    lime
    shap
